Feature - CO-1564: Add JSON:API relationships, example responses
osu-mist/edu-students-api pull request #2
Opened 2019-09-03 17:05 UTC by ianbrown9475

2019-09-03 23:23 UTC, tsoliangwu0130 requested changes

2019-09-03 23:23 UTC, tsoliangwu0130 commented on example-responses.md
> +        "self": "https://api.v1.oregonstate.edu/v1/students/{osuId}/class-schedule"
Not a big deal, but I think the hostname we usually use for the prod is `api.oregonstate.edu`.

2019-09-03 23:23 UTC, tsoliangwu0130 commented on example-responses.md
> +                "https://api.v1.oregonstate.edu/v1/education/offeringAssociations?filter[personId]=931123456"
Should this be `https://api.oregonstate.edu/v1/education/offering-associations`?

2019-09-03 23:23 UTC, tsoliangwu0130 commented on example-responses.md
> +    `GET /students/{osuId}/class-schedule?include=offeringAssociation`
To clarify, the value of `include` should be the `type` of related resource instead of the endpoint of the related resource, right?

2019-09-03 23:23 UTC, tsoliangwu0130 commented on example-responses.md
> +        "self": "https://api.v1.oregonstate.edu/v1/students/{osuId}/class-schedule"
Should this link contain `include` parameter as well?

2019-09-03 23:23 UTC, tsoliangwu0130 commented on example-responses.md
> +                "id": "string"
I'd suggest using fake IDs here to help people to understand the relationship between these nested resources.

2019-09-03 23:23 UTC, tsoliangwu0130 commented on openapi.yaml
> +
I guess we might also wanna return a 403 forbidden if include unpermitted resources?

2019-09-03 23:47 UTC, ianbrown9475 commented on example-responses.md
> +    `GET /students/{osuId}/class-schedule?include=offeringAssociation`
It should be the relationship name, which may be different from the `type` of the related resource. For example, here: https://github.com/osu-mist/edu-students-api/pull/2/files#diff-ff0421e216eb43f71bd093403990422bR453-R463 the relationship name is `degrees` but the type is `degree`.

2019-09-04 22:10 UTC, tsoliangwu0130 approved these changes

2019-09-05 15:40 UTC, merged